FROM ubuntu:latest
RUN apt-get update
RUN apt-get -y install git
RUN apt-get -y install default-jdk 
RUN apt-get -y install default-jre
RUN apt-get -y install maven 
COPY entrypoint.sh /entrypoint.sh
EXPOSE 6969
